CREATE TABLE IF NOT EXISTS jugadores (
  id SERIAL PRIMARY KEY,
  nombre VARCHAR(255) NOT NULL,
  posicion VARCHAR(255) NOT NULL,
  equipo VARCHAR(255) NOT NULL,
  dorsal INTEGER NOT NULL,
  valor_mercado DOUBLE PRECISION NOT NULL,
  activo BOOLEAN NOT NULL DEFAULT true
);
